eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        -  id: complaint-service
           uri: lb://complaint-service
           predicates:
             - Path=/api/complaint/**
        - id: user-management-service
          uri: lb://user-management-service
          predicates:
            - Path=/users/**
        - id: purchases-service
          uri: lb://purchases-service
          predicates:
            - Path=/purchases/**
        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          #for prod change TRACE to INFO
          gateway: TRACE
          gateway.route.RouteDefinitionLocator: INFO